#include <iostream>
#include <complex>
#include <cmath>
#include "approx.h"

// This part of the code i generated by AI, i have written the approx.h, approx.cc and Makefile files myself, 
int main() {
    using std::cout;
    using std::endl;
    using std::complex;

    const double pi = std::acos(-1.0);
    const complex<double> i(0.0, 1.0);

    complex<double> sqrt_minus_one = std::sqrt(complex<double>(-1.0, 0.0));
    complex<double> sqrt_i         = std::sqrt(i);
    complex<double> exp_i          = std::exp(i);
    complex<double> exp_i_pi       = std::exp(i * pi);
    complex<double> i_to_i         = std::pow(i, i);
    complex<double> log_i          = std::log(i);
    complex<double> sin_i_pi       = std::sin(i * pi);

    complex<double> expected_sqrt_minus_one(0.0, 1.0);
    complex<double> expected_sqrt_i(1.0 / std::sqrt(2.0), 1.0 / std::sqrt(2.0));
    complex<double> expected_exp_i(std::cos(1.0), std::sin(1.0));
    complex<double> expected_exp_i_pi(-1.0, 0.0);
    complex<double> expected_i_to_i(std::exp(-pi / 2.0), 0.0);
    complex<double> expected_log_i(0.0, pi / 2.0);
    complex<double> expected_sin_i_pi(0.0, std::sinh(pi));

    cout << "sqrt(-1) = " << sqrt_minus_one << endl;
    cout << "expected = " << expected_sqrt_minus_one << endl;
    cout << "approx?  = " << approx(sqrt_minus_one, expected_sqrt_minus_one) << endl;
    cout << endl;

    cout << "sqrt(i) = " << sqrt_i << endl;
    cout << "expected = " << expected_sqrt_i << endl;
    cout << "approx?  = " << approx(sqrt_i, expected_sqrt_i) << endl;
    cout << endl;

    cout << "exp(i) = " << exp_i << endl;
    cout << "expected = " << expected_exp_i << endl;
    cout << "approx?  = " << approx(exp_i, expected_exp_i) << endl;
    cout << endl;

    cout << "exp(i*pi) = " << exp_i_pi << endl;
    cout << "expected = " << expected_exp_i_pi << endl;
    cout << "approx?  = " << approx(exp_i_pi, expected_exp_i_pi) << endl;
    cout << endl;

    cout << "i^i = " << i_to_i << endl;
    cout << "expected = " << expected_i_to_i << endl;
    cout << "approx?  = " << approx(i_to_i, expected_i_to_i) << endl;
    cout << endl;

    cout << "log(i) = " << log_i << endl;
    cout << "expected = " << expected_log_i << endl;
    cout << "approx?  = " << approx(log_i, expected_log_i) << endl;
    cout << endl;

    cout << "sin(i*pi) = " << sin_i_pi << endl;
    cout << "expected = " << expected_sin_i_pi << endl;
    cout << "approx?  = " << approx(sin_i_pi, expected_sin_i_pi) << endl;
    cout << endl;

    // Extra: hyperbolic functions
    complex<double> sinh_i = std::sinh(i);
    complex<double> cosh_i = std::cosh(i);

    complex<double> expected_sinh_i(0.0, std::sin(1.0));
    complex<double> expected_cosh_i(std::cos(1.0), 0.0);

    cout << "sinh(i) = " << sinh_i << endl;
    cout << "expected = " << expected_sinh_i << endl;
    cout << "approx?  = " << approx(sinh_i, expected_sinh_i) << endl;
    cout << endl;

    cout << "cosh(i) = " << cosh_i << endl;
    cout << "expected = " << expected_cosh_i << endl;
    cout << "approx?  = " << approx(cosh_i, expected_cosh_i) << endl;
    cout << endl;

    cout << "Second branch of sqrt(i): "
         << -expected_sqrt_i << endl;

    return 0;
}